import json

data = {
  'title': 'Chapter 09 Public Health Ethics',
  'source_csv': 'chapter-09-public-health.csv',
  'shuffle_answers': True,
  'questions': []
}

mc_qs = [
  {'p': 'What is the primary unit of concern in public health ethics?', 'choices': ['The population as a whole', 'The individual patient', 'The healthcare provider', 'The medical institution']},
  {'p': 'How does public health ethics differ broadly from clinical ethics?', 'choices': ['It emphasizes collective welfare over individual autonomy', 'It relies entirely on randomized clinical trials', 'It only involves actions taken with strict personal consent', 'It focuses solely on extending the life of terminal patients']},
  {'p': 'What is John Stuart Mill\\'s harm principle?', 'choices': ['Power may only be rightfully exercised to prevent harm to others', 'Power may be used to protect a person from harming themselves', 'A society must maximize total well-being in all actions', 'All medical procedures require explicit written consent']},
  {'p': 'The historical case of Mary Mallon (Typhoid Mary) illustrates tensions between what?', 'choices': ['Individual liberty and collective welfare protection', 'Informed consent and clinical research protocols', 'Medical rationing and the difference principle', 'Paternalism and the right to refuse care']},
  {'p': 'What defines a "healthy carrier" in infectious disease?', 'choices': ['A person who spreads a disease without suffering from it themselves', 'A person who has fully recovered and is now immune', 'A vaccinated individual avoiding infection', 'A patient undergoing an active fever']},
  {'p': 'Under Jackson v. Massachusetts (1905), the Supreme Court ruled what?', 'choices': ['States can compel vaccination during a public health crisis', 'Individuals can always refuse vaccines based on liberty', 'State policies must be approved by the federal government directly', 'Quarantine is unconstitutional without a criminal conviction']},
  {'p': 'According to the deficit model, why do people hold false medical beliefs?', 'choices': ['Because they are missing correct factual information', 'Because they are trying to protect their group identity', 'Because they have been subjected to an echo chamber', 'Because they distrust scientific institutions on principle']},
  {'p': 'What does Dan Kahan mean by "identity-protective cognition"?', 'choices': ['People reason to protect their standing and identity within a group', 'People intentionally spread misinformation to harm other groups', 'People always defer to their primary physician out of identity', 'People systematically avoid learning scientific literacy']},
  {'p': 'According to Kahan, what happens when politically charged scientific questions are given to highly scientifically literate people?', 'choices': ['They become more polarized as they use knowledge to defend group beliefs', 'They immediately converge on the objectively true answer', 'They discard their group identity and agree entirely', 'They lose their scientific literacy temporarily']},
  {'p': 'What is an epistemic bubble according to C. Thi Nguyen?', 'choices': ['A network where contrary voices are accidentally excluded or missing', 'A network that actively discredits outside voices to pre-emptively dismiss them', 'A government propaganda strategy completely filtering the internet', 'An intentional manipulation of vaccine research data']},
  {'p': 'How does an echo chamber differ from an epistemic bubble?', 'choices': ['It actively discredits and builds distrust for outside voices', 'It just accidentally leaves out contrary information', 'It is inherently easier to pop by providing raw facts', 'It relies purely on the deficit model to maintain control']},
  {'p': 'In 1998, Dr. Andrew Wakefield published a flawed study claiming a link between the MMR vaccine and what?', 'choices': ['Autism in children', 'Adult onset diabetes', 'Guillain-Barre syndrome', 'Polio outbreaks']},
  {'p': 'What eventually happened to Wakefield\\'s 1998 paper in the Lancet?', 'choices': ['It was fully retracted and Wakefield lost his medical license', 'It was proven fully correct and adopted into policy globally', 'It sparked an FDA ban on the MMR vaccine', 'It was ignored entirely by the popular media']},
  {'p': 'What did journalist Brian Deer discover regarding Wakefield\\'s study?', 'choices': ['Wakefield had undisclosed financial conflicts and manipulated clinical data', 'Wakefield had actually stolen the data from another researcher entirely', 'Wakefield was forced to publish it by the NHS', 'Multinational pharmaceutical companies had funded the paper secretly']},
  {'p': 'What is "manufactured doubt"?', 'choices': ['A strategy to create scientific uncertainty where there is none to protect an industry', 'A natural phase of the scientific method during peer disagreement', 'A psychological instinct that protects personal group identity automatically', 'A legal standard used to block vaccine mandates']},
  {'p': 'Who developed the five justificatory benchmarks for evaluating public health interventions?', 'choices': ['Childress and colleagues', 'Amartya Sen and Nussbaum', 'Robert Nozick and Peter Singer', 'John Stuart Mill and John Rawls']},
  {'p': 'Which of the following is NOT one of the five justificatory benchmarks for public health?', 'choices': ['Paternalistic advantage over others', 'Effectiveness', 'Proportionality', 'Necessity']},
  {'p': 'What defines a "free rider" in the context of vaccination?', 'choices': ['A person who benefits from herd immunity without accepting the risk of the vaccine', 'A patient who refuses care because they lack insurance', 'A person who volunteers for experimental vaccine trials', 'A citizen who pays taxes specifically supporting public health']},
  {'p': 'What describes "herd immunity"?', 'choices': ['When enough of a population is immune that a disease cannot sustain spread', 'When every single person in a nation has received a particular vaccine', 'When an individual builds natural immunity through surviving an infection', 'When the government legally mandates a vaccine for school attendance']},
  {'p': 'Which public health benchmark requires calculating if the benefits outweigh the infringed moral considerations?', 'choices': ['Proportionality', 'Effectiveness', 'Least infringement', 'Necessity']},
  {'p': 'Which public health benchmark requires choosing the option completely fulfilling the goal while restricting liberty the least?', 'choices': ['Least infringement', 'Necessity', 'Proportionality', 'Effectiveness']},
  {'p': 'What was used as the central legal precedent in the infamous Buck v. Bell (1927) ruling?', 'choices': ['Jacobson v. Massachusetts', 'Cruzan v. Director', 'Roe v. Wade', 'The decision in Mary Mallon\\'s quarantine']},
  {'p': 'What catastrophic conclusion did Buck v. Bell legally defend using public health logic?', 'choices': ['Compulsory sterilization of the purportedly "feeble-minded"', 'Mandatory organ donations from death row inmates', 'Immediate euthanasia for psychiatric suffering alone', 'The indefinite detention of all healthy carriers uniformly']},
  {'p': 'If a false belief survives because it sits in an echo chamber, what is the best strategy?', 'choices': ['Rebuilding trust and relationship first', 'Supplying large packets of scientific studies', 'Explaining the deficit model in detail', 'Forcing the person to read opposing views only']},
  {'p': 'Why is public health ethics described as inherently political?', 'choices': ['It authorizes the state to use coercive power on the citizenry', 'It only involves voting on healthcare policies', 'It requires all decisions to pass through the Supreme Court', 'It is based entirely on campaign platforms rather than science']},
  {'p': 'What was Wakefield\\'s undisclosed financial conflict of interest?', 'choices': ['He was funded by lawyers suing vaccine manufacturers', 'He received huge payouts from foreign governments', 'He was selling a rival patent for the MMR vaccine exclusively', 'He was trying to short-sell the shares of the Lancet journal']},
  {'p': 'Why do public health interventions often face intense resistance?', 'choices': ['They burden some people for the benefit of others', 'They are entirely experimental and unproven', 'They focus solely on terminal individual patients', 'They require the explicit consent of every citizen linearly']},
  {'p': 'Naomi Oreskes asks "Why trust science?" and answers that trust is founded on what?', 'choices': ['The sustained critical consensus of a community of experts', 'The lone genius making breakthroughs entirely alone', 'Direct access to absolute untainted foundational truth', 'A strict adherence to the deficit model']},
  {'p': 'If a person refuses the MMR vaccine purely due to missing information, what condition are they in?', 'choices': ['They have a simple deficit that facts can actually fix', 'They are trapped in a deep echo chamber', 'They are acting out of identity-protective cognition primarily', 'They are deliberately free-riding on herd immunity']},
  {'p': 'Why did Mary Mallon\\'s second confinement feel more ethically justified than the first?', 'choices': ['She knew she was a carrier and voluntarily cooked anyway', 'She actively committed a violent federal crime', 'The laws had explicitly banned Irish immigrants', 'The Supreme Court issued a new ruling covering her specifically']}
]

mr_qs = [
  {'p': 'Which of the following are parts of Childress and colleagues\\' five justificatory benchmarks? (Select all that apply)', 'choices': ['Effectiveness', 'Proportionality', 'Necessity', 'Least infringement'], 'wrong': ['Financial maximum yield', 'Total elimination of risk']},
  {'p': 'What are defining features of an "echo chamber" according to Nguyen? (Select all that apply)', 'choices': ['Actively discredits outside voices', 'Preemptively dismisses contrary evidence', 'Builds distrust in mainstream sources'], 'wrong': ['Just accidentally leaves out information', 'Easily popped by presenting raw facts']},
  {'p': 'Which arguments did the Supreme Court use in Jacobson v. Massachusetts? (Select all that apply)', 'choices': ['Liberty is not an absolute right to harm others', 'States have police power to protect public safety', 'Compelled vaccination is constitutional during outbreaks'], 'wrong': ['Forced sterilization is a vital component of public health', 'The federal government directs all state health boards']},
  {'p': 'What was true regarding Mary Mallon\\'s first confinement? (Select all that apply)', 'choices': ['She had committed no crime', 'She felt entirely healthy', 'There was no specific law allowing quarantine of healthy carriers yet'], 'wrong': ['She had explicitly admitted to spreading typhoid', 'It lasted until her death without release']},
  {'p': 'What did Dan Kahan\\'s research on identity-protective cognition show? (Select all that apply)', 'choices': ['Reasoning is used to protect standing in a group', 'High science literacy increases polarization on charged issues', 'Minds often prioritize group alignment over truth'], 'wrong': ['The deficit model is perfectly accurate', 'Only uneducated individuals reject science']},
  {'p': 'What elements contributed to the lasting impact of the Wakefield MMR study? (Select all that apply)', 'choices': ['It was published in the prestigious Lancet medical journal', 'It matched existing anxieties about modern medicine and autism', 'It enjoyed uncritical spread by early media reports'], 'wrong': ['It involved hundreds of thousands of clinically verified test subjects', 'The FDA formally endorsed it initially']},
  {'p': 'What ethical principles must often be balanced in public health decisions? (Select all that apply)', 'choices': ['Collective welfare or beneficence', 'Individual autonomy or liberty', 'Justice or fairness in distribution of burdens'], 'wrong': ['Absolute right to refuse any regulation', 'Market forces as the primary determinant']},
  {'p': 'Which statements describe a "free rider" problem in public health vaccination? (Select all that apply)', 'choices': ['Individuals gain protection from the vaccinated majority', 'Individuals avoid the risk of the vaccine themselves', 'It leverages the immunity of the herd unfairly'], 'wrong': ['Individuals pay extreme out-of-pocket costs for others', 'It only involves patients actively isolated in quarantine']},
  {'p': 'What does Naomi Oreskes argue regarding trusting science? (Select all that apply)', 'choices': ['Science is a social, consensus-building process', 'Trust should be based on the community of experts checking each other', 'Individual studies can be flawed but the process corrects over time'], 'wrong': ['We must trust science because it has direct access to absolute truth', 'Consensus is irrelevant to scientific factuality']},
  {'p': 'How do epistemic bubbles differ from echo chambers according to Nguyen? (Select all that apply)', 'choices': ['Bubbles involve accidentally missing voices', 'Bubbles are structurally easier to fix by adding information', 'Echo chambers involve active distrust of outside voices'], 'wrong': ['Echo chambers are just innocent filter bubbles', 'Bubbles actively attack and discredit opposing arguments']}
]

for q in mc_qs:
  data['questions'].append({'question_type': 'MC', 'answer_style': 'clause', 'prompt': q['p'], 'answer_explanation': '', 'points': '', 'tags': ['chapter-09', 'mc'], 'choices': [{'text': c, 'correct': i==0} for i, c in enumerate(q['choices'])]})
for q in mr_qs:
  data['questions'].append({'question_type': 'MR', 'answer_style': 'clause', 'prompt': q['p'], 'answer_explanation': '', 'points': '', 'tags': ['chapter-09', 'mr'], 'choices': [{'text': c, 'correct': True} for c in q['choices']] + [{'text': c, 'correct': False} for c in q['wrong']]})

with open('perrusall_quizzes/sources/chapter-09-public-health.quiz.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)
