<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brendan Shea, PhD">
<meta name="dcterms.date" content="last-modified">

<title>Lecture 12 — Animal Ethics – Bioethics: An Open Educational Resource</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles/custom.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Bioethics: An Open Educational Resource</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/00-course-outline.html"> 
<span class="menu-text">Outline</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/brendanpshea/bioethics-oer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/12a-animal-moral-status.html">12. Animal Ethics</a></li><li class="breadcrumb-item"><a href="../chapters/12b-industrial-xeno.html">Part B — Industrial Animals, Xenotransplantation, and the Frontier</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/00-course-outline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Outline</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/00b-god-committee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 0 — Who Shall Live?</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">1. Principles &amp; Reasoning</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — The Four Principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01b-theories.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Ethical Theories</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">2. History &amp; Relationship</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02a-history.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — History</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02b-clinical-relationship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Clinical Relationship</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">3. Research Ethics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03a-clinical-research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — How Clinical Research Works</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03b-protecting-research-subjects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Protecting Research Subjects</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">4. Abortion</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04a-abortion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Moral Status</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04b-abortion-law.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Law &amp; Cases</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">5. Autonomy, Paternalism, and Reproduction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05a-paternalism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Paternalism &amp; Its Limits</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05b-reproductive-markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Markets &amp; Surrogacy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">6. Genomics &amp; Enhancement</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06a-genomics-reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Reading Genomes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06b-genomics-enhancement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Engineering Persons</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">7. End-of-Life Care</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07a-death-dying.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Death, Dying &amp; Advance Planning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07b-euthanasia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Euthanasia &amp; Assisted Death</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">8. Justice &amp; Health Care</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08a-justice-health.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Theories of Justice &amp; the Right to Care</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08b-us-healthcare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Why US Health Care Costs So Much</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">9. Public Health Ethics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09a-public-health.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — From Patient to Population</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09b-public-health-beliefs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — False Beliefs &amp; the Ethics of Correction</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">10. AI in Medicine</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10a-medical-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — How Medical AI Works and Where It Goes Wrong</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10b-fifth-principle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — The Fifth Principle: Consent, Accountability, and Black Boxes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">11. Gender, Identity &amp; Disability</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11a-gender-affirming-care.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Gender-Affirming Care: Deciding Under Uncertainty</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11b-disability-identity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part B — Disability, Identity, and the Limits of Autonomy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">12. Animal Ethics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12a-animal-moral-status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part A — Moral Status of Animals and the Ethics of Research</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12b-industrial-xeno.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Part B — Industrial Animals, Xenotransplantation, and the Frontier</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rank-these-four" id="toc-rank-these-four" class="nav-link active" data-scroll-target="#rank-these-four"><span class="header-section-number">1</span> Rank These Four</a>
  <ul class="collapse">
  <li><a href="#a-case-to-sit-with" id="toc-a-case-to-sit-with" class="nav-link" data-scroll-target="#a-case-to-sit-with"><span class="header-section-number">1.1</span> A Case to Sit With</a></li>
  <li><a href="#after-youve-discussed" id="toc-after-youve-discussed" class="nav-link" data-scroll-target="#after-youve-discussed"><span class="header-section-number">1.2</span> After You’ve Discussed</a></li>
  <li><a href="#where-we-left-off" id="toc-where-we-left-off" class="nav-link" data-scroll-target="#where-we-left-off"><span class="header-section-number">1.3</span> Where We Left Off</a></li>
  <li><a href="#today" id="toc-today" class="nav-link" data-scroll-target="#today"><span class="header-section-number">1.4</span> Today</a></li>
  </ul></li>
  <li><a href="#the-biggest-use-the-food-system" id="toc-the-biggest-use-the-food-system" class="nav-link" data-scroll-target="#the-biggest-use-the-food-system"><span class="header-section-number">2</span> The Biggest Use: The Food System</a>
  <ul class="collapse">
  <li><a href="#the-scale-is-the-argument" id="toc-the-scale-is-the-argument" class="nav-link" data-scroll-target="#the-scale-is-the-argument"><span class="header-section-number">2.1</span> The Scale Is the Argument</a></li>
  <li><a href="#what-that-number-looks-like" id="toc-what-that-number-looks-like" class="nav-link" data-scroll-target="#what-that-number-looks-like"><span class="header-section-number">2.2</span> What That Number Looks Like</a></li>
  <li><a href="#it-harms-humans-too-antibiotics" id="toc-it-harms-humans-too-antibiotics" class="nav-link" data-scroll-target="#it-harms-humans-too-antibiotics"><span class="header-section-number">2.3</span> It Harms Humans Too: Antibiotics</a></li>
  <li><a href="#it-harms-humans-too-pandemics" id="toc-it-harms-humans-too-pandemics" class="nav-link" data-scroll-target="#it-harms-humans-too-pandemics"><span class="header-section-number">2.4</span> It Harms Humans Too: Pandemics</a></li>
  <li><a href="#thought-question" id="toc-thought-question" class="nav-link" data-scroll-target="#thought-question"><span class="header-section-number">2.5</span> Thought Question</a></li>
  <li><a href="#after-youve-discussed-1" id="toc-after-youve-discussed-1" class="nav-link" data-scroll-target="#after-youve-discussed-1"><span class="header-section-number">2.6</span> After You’ve Discussed</a></li>
  </ul></li>
  <li><a href="#does-the-research-even-work" id="toc-does-the-research-even-work" class="nav-link" data-scroll-target="#does-the-research-even-work"><span class="header-section-number">3</span> Does the Research Even Work?</a>
  <ul class="collapse">
  <li><a href="#the-translation-gap" id="toc-the-translation-gap" class="nav-link" data-scroll-target="#the-translation-gap"><span class="header-section-number">3.1</span> The Translation Gap</a></li>
  <li><a href="#why-the-gap-is-an-ethical-argument" id="toc-why-the-gap-is-an-ethical-argument" class="nav-link" data-scroll-target="#why-the-gap-is-an-ethical-argument"><span class="header-section-number">3.2</span> Why the Gap Is an Ethical Argument</a></li>
  <li><a href="#what-the-regulators-are-doing" id="toc-what-the-regulators-are-doing" class="nav-link" data-scroll-target="#what-the-regulators-are-doing"><span class="header-section-number">3.3</span> What the Regulators Are Doing</a></li>
  <li><a href="#the-honest-reply" id="toc-the-honest-reply" class="nav-link" data-scroll-target="#the-honest-reply"><span class="header-section-number">3.4</span> The Honest Reply</a></li>
  </ul></li>
  <li><a href="#the-high-tech-low-number-use" id="toc-the-high-tech-low-number-use" class="nav-link" data-scroll-target="#the-high-tech-low-number-use"><span class="header-section-number">4</span> The High-Tech, Low-Number Use</a>
  <ul class="collapse">
  <li><a href="#why-xenotransplantation" id="toc-why-xenotransplantation" class="nav-link" data-scroll-target="#why-xenotransplantation"><span class="header-section-number">4.1</span> Why Xenotransplantation</a></li>
  <li><a href="#how-you-build-a-transplant-pig" id="toc-how-you-build-a-transplant-pig" class="nav-link" data-scroll-target="#how-you-build-a-transplant-pig"><span class="header-section-number">4.2</span> How You Build a Transplant Pig</a></li>
  <li><a href="#the-cases-so-far" id="toc-the-cases-so-far" class="nav-link" data-scroll-target="#the-cases-so-far"><span class="header-section-number">4.3</span> The Cases So Far</a></li>
  <li><a href="#what-makes-xeno-ethically-distinct" id="toc-what-makes-xeno-ethically-distinct" class="nav-link" data-scroll-target="#what-makes-xeno-ethically-distinct"><span class="header-section-number">4.4</span> What Makes Xeno Ethically Distinct</a></li>
  <li><a href="#make-it-contemporary" id="toc-make-it-contemporary" class="nav-link" data-scroll-target="#make-it-contemporary"><span class="header-section-number">4.5</span> Make It Contemporary</a></li>
  </ul></li>
  <li><a href="#the-ranking-that-surprises-people" id="toc-the-ranking-that-surprises-people" class="nav-link" data-scroll-target="#the-ranking-that-surprises-people"><span class="header-section-number">5</span> The Ranking That Surprises People</a>
  <ul class="collapse">
  <li><a href="#the-ledger" id="toc-the-ledger" class="nav-link" data-scroll-target="#the-ledger"><span class="header-section-number">5.1</span> The Ledger</a></li>
  <li><a href="#filling-it-in" id="toc-filling-it-in" class="nav-link" data-scroll-target="#filling-it-in"><span class="header-section-number">5.2</span> Filling It In</a></li>
  <li><a href="#why-singer-accepts-the-pig-heart" id="toc-why-singer-accepts-the-pig-heart" class="nav-link" data-scroll-target="#why-singer-accepts-the-pig-heart"><span class="header-section-number">5.3</span> Why Singer Accepts the Pig Heart</a></li>
  <li><a href="#why-regan-wont-rank-them" id="toc-why-regan-wont-rank-them" class="nav-link" data-scroll-target="#why-regan-wont-rank-them"><span class="header-section-number">5.4</span> Why Regan Won’t Rank Them</a></li>
  </ul></li>
  <li><a href="#the-frontier-smarter-animals" id="toc-the-frontier-smarter-animals" class="nav-link" data-scroll-target="#the-frontier-smarter-animals"><span class="header-section-number">6</span> The Frontier: Smarter Animals</a>
  <ul class="collapse">
  <li><a href="#uplifting" id="toc-uplifting" class="nav-link" data-scroll-target="#uplifting"><span class="header-section-number">6.1</span> Uplifting</a></li>
  <li><a href="#the-paradox" id="toc-the-paradox" class="nav-link" data-scroll-target="#the-paradox"><span class="header-section-number">6.2</span> The Paradox</a></li>
  <li><a href="#its-already-real" id="toc-its-already-real" class="nav-link" data-scroll-target="#its-already-real"><span class="header-section-number">6.3</span> It’s Already Real</a></li>
  <li><a href="#thought-question-1" id="toc-thought-question-1" class="nav-link" data-scroll-target="#thought-question-1"><span class="header-section-number">6.4</span> Thought Question</a></li>
  <li><a href="#after-youve-discussed-2" id="toc-after-youve-discussed-2" class="nav-link" data-scroll-target="#after-youve-discussed-2"><span class="header-section-number">6.5</span> After You’ve Discussed</a></li>
  </ul></li>
  <li><a href="#connecting-threads" id="toc-connecting-threads" class="nav-link" data-scroll-target="#connecting-threads"><span class="header-section-number">7</span> Connecting Threads</a>
  <ul class="collapse">
  <li><a href="#the-course-applied-to-animals" id="toc-the-course-applied-to-animals" class="nav-link" data-scroll-target="#the-course-applied-to-animals"><span class="header-section-number">7.1</span> The Course, Applied to Animals</a></li>
  <li><a href="#thread-1-the-argument-from-abortion" id="toc-thread-1-the-argument-from-abortion" class="nav-link" data-scroll-target="#thread-1-the-argument-from-abortion"><span class="header-section-number">7.2</span> Thread 1 — The Argument from Abortion</a></li>
  <li><a href="#threads-2-and-3-genetics-and-end-of-life" id="toc-threads-2-and-3-genetics-and-end-of-life" class="nav-link" data-scroll-target="#threads-2-and-3-genetics-and-end-of-life"><span class="header-section-number">7.3</span> Threads 2 and 3 — Genetics and End of Life</a></li>
  </ul></li>
  <li><a href="#where-this-leaves-us" id="toc-where-this-leaves-us" class="nav-link" data-scroll-target="#where-this-leaves-us"><span class="header-section-number">8</span> Where This Leaves Us</a>
  <ul class="collapse">
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up"><span class="header-section-number">8.1</span> Wrap-Up</a></li>
  <li><a href="#paired-case" id="toc-paired-case" class="nav-link" data-scroll-target="#paired-case"><span class="header-section-number">8.2</span> Paired Case</a></li>
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions"><span class="header-section-number">8.3</span> Review Questions</a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">8.4</span> Key Terms</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">8.5</span> Further Reading</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8.6</span> References</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="12b-industrial-xeno-slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/12a-animal-moral-status.html">12. Animal Ethics</a></li><li class="breadcrumb-item"><a href="../chapters/12b-industrial-xeno.html">Part B — Industrial Animals, Xenotransplantation, and the Frontier</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Lecture 12 — Animal Ethics</h1>
<p class="subtitle lead">Part B: Industrial Animals, Xenotransplantation, and the Frontier</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Brendan Shea, PhD </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            An Introduction to Bioethics.
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="rank-these-four" class="level1 section-divider" data-number="1">
<h1 class="section-divider" data-number="1"><span class="header-section-number">1</span> Rank These Four</h1>
<section id="a-case-to-sit-with" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="a-case-to-sit-with"><span class="header-section-number">1.1</span> A Case to Sit With</h2>
<div class="thought-question">
<p>Here are four ways humans use animals. Put them in order, from <strong>most defensible</strong> to <strong>least</strong>:</p>
<ol type="1">
<li><strong>Bacon</strong> from a factory-farmed pig.</li>
<li>A <strong>rabbit</strong> used to test a new mascara for eye irritation.</li>
<li>A <strong>gene-edited pig</strong> whose heart is transplanted into a dying patient.</li>
<li>A <strong>lab mouse</strong> engineered to be smarter, to make a better research subject.</li>
</ol>
<p>Then answer:</p>
<ul>
<li>What did you put <strong>last</strong>, and what rule were you using?</li>
<li>Did “high-tech” or “unnatural” push anything <em>down</em> your list? Should it?</li>
</ul>
</div>
</section>
<section id="after-youve-discussed" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="after-youve-discussed"><span class="header-section-number">1.2</span> After You’ve Discussed</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most people rank the pig-heart transplant as more troubling than the bacon. Hold that intuition up to the light.</p>
<p>By the end of today, we’ll have a tool that ranks animal uses by three things — <strong>scale, necessity, and benefit</strong> — and on that tool, the everyday cheeseburger comes out <em>worse</em> than the high-tech transplant. Whether you accept that result, or reject the tool, is the work of this lecture.</p>
</div>
</div>
</section>
<section id="where-we-left-off" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="where-we-left-off"><span class="header-section-number">1.3</span> Where We Left Off</h2>
<p>In Part A we asked <strong>which beings have moral status</strong> and met five answers — Kant, Singer, Regan, Cohen, Korsgaard. We saw that the <strong>3 Rs</strong> and the <strong>IACUC</strong> try to shrink and police the harm of research.</p>
<p>Today we leave the lab. The same views now have to handle the two largest and most advanced uses of animals: the food system that kills tens of billions, and the gene-edited pigs now keeping humans alive.</p>
</section>
<section id="today" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="today"><span class="header-section-number">1.4</span> Today</h2>
<div class="learning-outcomes">
<p>By the end of Part B, you will be able to:</p>
<ul>
<li>Explain how industrial animal agriculture harms <strong>animals and humans</strong> — including antibiotic resistance and zoonotic risk.</li>
<li>State the <strong>translation-gap</strong> critique of animal research and what the FDA and EU are doing about it.</li>
<li>Describe how a pig is <strong>gene-edited</strong> for transplant and the ethical issues unique to xenotransplantation.</li>
<li>Use the <strong>scale–necessity–benefit</strong> ledger to explain why a critic of factory farming can still accept pig-heart transplants — and how Regan resists that ranking.</li>
<li>Connect animal ethics to <strong>moral status, enhancement, and end-of-life</strong> arguments from earlier in the course.</li>
</ul>
</div>
</section>
</section>
<section id="the-biggest-use-the-food-system" class="level1 section-divider" data-number="2">
<h1 class="section-divider" data-number="2"><span class="header-section-number">2</span> The Biggest Use: The Food System</h1>
<section id="the-scale-is-the-argument" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-scale-is-the-argument"><span class="header-section-number">2.1</span> The Scale Is the Argument</h2>
<p>Whatever you think of eating meat, start with the number.</p>
<ul>
<li>Humans raise and kill roughly <strong>80 billion land animals a year</strong> — about ten per person on Earth — the overwhelming majority on industrial farms.</li>
<li>Most live in <span class="key-term">CAFOs</span> (concentrated animal feeding operations): thousands of animals indoors at high density, bred for fast growth, with little room to move.</li>
<li>Recall Singer from Part A: this inflicts vast suffering for an interest — taste, cost, convenience — that is, for most of us, <strong>minor and replaceable.</strong> On his view it is the clearest wrong in the whole field.</li>
</ul>
<p>The scale matters morally: a practice repeated 80 billion times needs a justification 80 billion times as strong.</p>
</section>
<section id="what-that-number-looks-like" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="what-that-number-looks-like"><span class="header-section-number">2.2</span> What That Number Looks Like</h2>
<p><img src="../images/cafo_aerial.jpg" class="img-fluid" style="width:78.0%" alt="Aerial view of a concentrated animal feeding operation: rows of long metal barns surrounded by bare ground and waste lagoons"></p>
<div class="attribution">
<p>Socially Responsible Agricultural Project, via Wikimedia Commons. CC BY 4.0.</p>
</div>
<p>Each of those barns holds thousands of animals that will never go outside. This is what 80 billion a year requires.</p>
</section>
<section id="it-harms-humans-too-antibiotics" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="it-harms-humans-too-antibiotics"><span class="header-section-number">2.3</span> It Harms Humans Too: Antibiotics</h2>
<p>The welfare case is not the only case. Factory farming is also a <strong>public-health</strong> problem — which means even a strictly human-centered ethics has to reckon with it.</p>
<ul>
<li>The majority of antibiotics sold in the U.S. go to <strong>livestock</strong>, not people — often to healthy animals, to speed growth and prevent disease in crowded barns.</li>
<li>Constant low-dose exposure breeds <span class="key-term">antibiotic resistance</span>: bacteria that survive the drugs, then spread to humans through food, water, and workers.</li>
<li>A major 2016 review projected that drug-resistant infections could cause <strong>10 million deaths a year by 2050</strong> if unchecked — outpacing cancer <span class="citation" data-cites="oneill2016_amr">(<a href="#ref-oneill2016_amr" role="doc-biblioref">O’Neill 2016</a>)</span>.</li>
</ul>
<p>The pig in the barn and the patient whose antibiotics no longer work are linked by the same practice.</p>
</section>
<section id="it-harms-humans-too-pandemics" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="it-harms-humans-too-pandemics"><span class="header-section-number">2.4</span> It Harms Humans Too: Pandemics</h2>
<p>The second human cost is the one we just lived through.</p>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>Crowding genetically similar animals together is ideal for breeding new viruses. <strong>Avian</strong> and <strong>swine influenza</strong> strains have jumped from farms to people.</li>
<li>Most experts count industrial animal agriculture and the wildlife trade among the leading <strong>pandemic risks</strong> of the century.</li>
</ul>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:44%;">
<p><strong>The convergence.</strong> Kant and Cohen grant animals no rights — yet their human-centered view still <strong>condemns</strong> a system that breeds resistant bacteria and pandemic flu.</p>
<p>Welfare reasons and self-interested human reasons point the <em>same</em> way here. That is rare, and worth noticing.</p>
</div>
</div>
</section>
<section id="thought-question" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="thought-question"><span class="header-section-number">2.5</span> Thought Question</h2>
<div class="thought-question">
<p>A hospital you work at sources its cafeteria meat from conventional industrial farms. A nurses’ group proposes switching to higher-welfare, antibiotic-free suppliers — at higher cost, paid from the same budget that funds patient programs.</p>
<ol type="1">
<li>Is this an animal-welfare decision, a public-health decision, or both?</li>
<li>As a nurse, can you justify the extra cost to a patient whose program might be trimmed to pay for it?</li>
<li>Would Cohen — who grants animals no rights — have any reason to support the switch?</li>
</ol>
</div>
</section>
<section id="after-youve-discussed-1" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="after-youve-discussed-1"><span class="header-section-number">2.6</span> After You’ve Discussed</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A distinction the food case forces: <strong>direct vs.&nbsp;indirect harm.</strong></p>
<p>The factory farm harms the pig <strong>directly</strong> — that is the welfare wrong. It also harms <em>humans</em> <strong>indirectly</strong>, through resistant bacteria and new viruses — a second, separate wrong with different victims.</p>
<p>Why this matters: the two harms come apart. A reform could ease the public-health harm (ban growth-promoter antibiotics) while leaving the welfare harm untouched — and vice versa. Knowing <em>which</em> harm a policy fixes keeps you from claiming credit for both.</p>
</div>
</div>
</section>
</section>
<section id="does-the-research-even-work" class="level1 section-divider" data-number="3">
<h1 class="section-divider" data-number="3"><span class="header-section-number">3</span> Does the Research Even Work?</h1>
<section id="the-translation-gap" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="the-translation-gap"><span class="header-section-number">3.1</span> The Translation Gap</h2>
<p>Part A defended research by its benefits. But a benefit you don’t get can’t justify a harm — and animal models often don’t deliver.</p>
<ul>
<li>Around <strong>9 of every 10 drugs</strong> that pass animal safety and efficacy tests still <strong>fail in human trials</strong> — for lack of effect, or for toxicity the animals never showed.</li>
<li>Species differ in ways that matter: a compound safe in mice can poison people, and a disease “cured” in a mouse routinely does nothing in patients.</li>
<li>This is the <span class="key-term">translation gap</span>: the distance between “it worked in the animal” and “it works in the human.”</li>
</ul>
</section>
<section id="why-the-gap-is-an-ethical-argument" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="why-the-gap-is-an-ethical-argument"><span class="header-section-number">3.2</span> Why the Gap Is an Ethical Argument</h2>
<p>The translation gap turns a scientific fact into a moral one.</p>
<ul>
<li>The Part A defense was a <strong>cost-benefit</strong> trade: animal suffering is the price of human benefit. But if the data transfer poorly, the benefit shrinks — and the trade gets worse.</li>
<li>This doesn’t show research is <em>worthless</em>; it shows the burden of proof is higher than the old “animals first, always” rule assumed.</li>
<li>Critics push further: in some fields, <strong>human-based methods may predict human outcomes better</strong> than the animal model they’d replace — making the animal use not just costly but inferior.</li>
</ul>
<div id="a3f444c9" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="12b-industrial-xeno_files/figure-html/cell-2-output-1.png" width="701" height="250" class="figure-img"></p>
<figcaption>The drug-development attrition funnel: most compounds that clear animal testing still fail in humans (illustrative proportions).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-the-regulators-are-doing" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="what-the-regulators-are-doing"><span class="header-section-number">3.3</span> What the Regulators Are Doing</h2>
<p>For the first time, law is moving away from mandatory animal testing.</p>
<ul>
<li>The U.S. <strong>FDA Modernization Act 2.0 (2022)</strong> ended the blanket requirement that new drugs be animal-tested, allowing validated <strong>non-animal methods</strong> — organ-on-a-chip, cell models, computer simulation <span class="citation" data-cites="fda_modernization2022">(<a href="#ref-fda_modernization2022" role="doc-biblioref">United States Congress 2022</a>)</span>.</li>
<li>The <strong>European Union</strong> has committed to a <strong>roadmap to phase out animal testing</strong> for chemical safety, setting milestones toward replacement <span class="citation" data-cites="ec2025_roadmap">(<a href="#ref-ec2025_roadmap" role="doc-biblioref">European Commission 2025</a>)</span>.</li>
<li>Direction of travel: from “animals unless impossible” toward “non-animal where validated.”</li>
</ul>
</section>
<section id="the-honest-reply" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="the-honest-reply"><span class="header-section-number">3.4</span> The Honest Reply</h2>
<p>Balance matters: the phase-out is a goal, not a finished capability.</p>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>A chip with human cells can model a liver’s response — but <strong>not</strong> a whole immune system, a developing brain, or a years-long disease.</li>
<li>For now, some questions genuinely require a living, whole organism. The replacements are improving fast but are <strong>not yet complete</strong>.</li>
</ul>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:44%;">
<p>So the debate is no longer “research: yes or no?” It is <strong>how fast</strong> we can replace it, and <strong>who bears the risk</strong> of moving before the alternatives are proven.</p>
<p>Singer and Regan both welcome replacement — for different reasons. Less suffering; fewer rights violated.</p>
</div>
</div>
</section>
</section>
<section id="the-high-tech-low-number-use" class="level1 section-divider" data-number="4">
<h1 class="section-divider" data-number="4"><span class="header-section-number">4</span> The High-Tech, Low-Number Use</h1>
<section id="why-xenotransplantation" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="why-xenotransplantation"><span class="header-section-number">4.1</span> Why Xenotransplantation</h2>
<p>The pressure behind it is a body count of a different kind.</p>
<ul>
<li>More than <strong>108,000 Americans</strong> were on the transplant waiting list as of late 2025 — about <strong>94,000</strong> of them waiting for a kidney; roughly <strong>17 die each day</strong> before an organ arrives.</li>
<li><span class="key-term">Xenotransplantation</span> — transplanting organs from another species — promises an unlimited supply, grown to order.</li>
<li>The species of choice is the <strong>pig</strong>: organs the right size, fast breeding, decades of surgical familiarity. The obstacle was always rejection — the human body destroys pig tissue within minutes.</li>
</ul>
</section>
<section id="how-you-build-a-transplant-pig" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="how-you-build-a-transplant-pig"><span class="header-section-number">4.2</span> How You Build a Transplant Pig</h2>
<p>The breakthrough was genetic, not surgical. CRISPR lets researchers edit a pig so its organs survive in a human body.</p>
<div class="cell" data-fig-width="9.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<svg width="912" height="480" viewbox="0.00 0.00 644.97 65.60" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 61.6)">
<title>xeno</title>
<!-- a -->
<g id="node1" class="node">
<title>a</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M135.66,-57.4C135.66,-57.4 11.78,-57.4 11.78,-57.4 5.78,-57.4 -0.22,-51.4 -0.22,-45.4 -0.22,-45.4 -0.22,-12.2 -0.22,-12.2 -0.22,-6.2 5.78,-0.2 11.78,-0.2 11.78,-0.2 135.66,-0.2 135.66,-0.2 141.66,-0.2 147.66,-6.2 147.66,-12.2 147.66,-12.2 147.66,-45.4 147.66,-45.4 147.66,-51.4 141.66,-57.4 135.66,-57.4"></path>
<text text-anchor="middle" x="73.72" y="-38.7" font-family="Inter" font-size="11.00" fill="#0f172a">Knock OUT pig genes</text>
<text text-anchor="middle" x="73.72" y="-25.5" font-family="Inter" font-size="11.00" fill="#0f172a">• alpha-gal &amp; other sugars</text>
<text text-anchor="middle" x="73.72" y="-12.3" font-family="Inter" font-size="11.00" fill="#0f172a"> &nbsp;(trigger instant rejection)</text>
</g>
<!-- b -->
<g id="node2" class="node">
<title>b</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M308.05,-57.4C308.05,-57.4 195.57,-57.4 195.57,-57.4 189.57,-57.4 183.57,-51.4 183.57,-45.4 183.57,-45.4 183.57,-12.2 183.57,-12.2 183.57,-6.2 189.57,-0.2 195.57,-0.2 195.57,-0.2 308.05,-0.2 308.05,-0.2 314.05,-0.2 320.05,-6.2 320.05,-12.2 320.05,-12.2 320.05,-45.4 320.05,-45.4 320.05,-51.4 314.05,-57.4 308.05,-57.4"></path>
<text text-anchor="middle" x="251.81" y="-38.7" font-family="Inter" font-size="11.00" fill="#0f172a">Inactivate PERVs</text>
<text text-anchor="middle" x="251.81" y="-25.5" font-family="Inter" font-size="11.00" fill="#0f172a">• pig retroviruses in the</text>
<text text-anchor="middle" x="251.81" y="-12.3" font-family="Inter" font-size="11.00" fill="#0f172a"> &nbsp;genome (infection risk)</text>
</g>
<!-- a&#45;&gt;b -->
<g id="edge1" class="edge">
<title>a-&gt;b</title>
<path fill="none" stroke="#0e7c86" stroke-width="1.3" d="M147.61,-28.8C156.02,-28.8 164.62,-28.8 173.09,-28.8"></path>
<polygon fill="#0e7c86" stroke="#0e7c86" stroke-width="1.3" points="183.33,-28.8 173.33,-33.3 178.33,-28.95 173.33,-28.95 173.33,-28.8 173.33,-28.65 178.33,-28.65 173.33,-24.3 183.33,-28.8 183.33,-28.8"></polygon>
</g>
<!-- c -->
<g id="node3" class="node">
<title>c</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M476.43,-57.4C476.43,-57.4 368.1,-57.4 368.1,-57.4 362.1,-57.4 356.1,-51.4 356.1,-45.4 356.1,-45.4 356.1,-12.2 356.1,-12.2 356.1,-6.2 362.1,-0.2 368.1,-0.2 368.1,-0.2 476.43,-0.2 476.43,-0.2 482.43,-0.2 488.43,-6.2 488.43,-12.2 488.43,-12.2 488.43,-45.4 488.43,-45.4 488.43,-51.4 482.43,-57.4 476.43,-57.4"></path>
<text text-anchor="middle" x="422.26" y="-38.7" font-family="Inter" font-size="11.00" fill="#0f172a">Knock IN human genes</text>
<text text-anchor="middle" x="422.26" y="-25.5" font-family="Inter" font-size="11.00" fill="#0f172a">• regulate clotting &amp;</text>
<text text-anchor="middle" x="422.26" y="-12.3" font-family="Inter" font-size="11.00" fill="#0f172a"> &nbsp;inflammation</text>
</g>
<!-- b&#45;&gt;c -->
<g id="edge2" class="edge">
<title>b-&gt;c</title>
<path fill="none" stroke="#0e7c86" stroke-width="1.3" d="M320.36,-28.8C328.84,-28.8 337.56,-28.8 346.16,-28.8"></path>
<polygon fill="#0e7c86" stroke="#0e7c86" stroke-width="1.3" points="356.17,-28.8 346.17,-33.3 351.17,-28.95 346.17,-28.95 346.17,-28.8 346.17,-28.65 351.17,-28.65 346.17,-24.3 356.17,-28.8 356.17,-28.8"></polygon>
</g>
<!-- d -->
<g id="node4" class="node">
<title>d</title>
<path fill="#0e7c86" stroke="#095058" stroke-width="1.4" d="M624.79,-51.2C624.79,-51.2 536.53,-51.2 536.53,-51.2 530.53,-51.2 524.53,-45.2 524.53,-39.2 524.53,-39.2 524.53,-18.4 524.53,-18.4 524.53,-12.4 530.53,-6.4 536.53,-6.4 536.53,-6.4 624.79,-6.4 624.79,-6.4 630.79,-6.4 636.79,-12.4 636.79,-18.4 636.79,-18.4 636.79,-39.2 636.79,-39.2 636.79,-45.2 630.79,-51.2 624.79,-51.2"></path>
<text text-anchor="middle" x="580.66" y="-32.1" font-family="Inter" font-size="11.00" fill="#ffffff">Pig organ tolerated</text>
<text text-anchor="middle" x="580.66" y="-18.9" font-family="Inter" font-size="11.00" fill="#ffffff">by the human body</text>
</g>
<!-- c&#45;&gt;d -->
<g id="edge3" class="edge">
<title>c-&gt;d</title>
<path fill="none" stroke="#0e7c86" stroke-width="1.3" d="M488.68,-28.8C497.13,-28.8 505.79,-28.8 514.24,-28.8"></path>
<polygon fill="#0e7c86" stroke="#0e7c86" stroke-width="1.3" points="524.42,-28.8 514.42,-33.3 519.42,-28.95 514.42,-28.95 514.42,-28.8 514.42,-28.65 519.42,-28.65 514.42,-24.3 524.42,-28.8 524.42,-28.8"></polygon>
</g>
</g>
</svg>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>A transplant pig may carry <strong>a dozen or more edits</strong> — some removing pig features the body attacks, some adding human ones it accepts.</p>
</section>
<section id="the-cases-so-far" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="the-cases-so-far"><span class="header-section-number">4.3</span> The Cases So Far</h2>
<p>The era of human xenotransplantation began in 2022 and is moving fast — fast enough that this chart needs checking every term.</p>
<div id="cell-fig-xeno-survival" class="cell" data-fig-height="4" data-fig-width="9.5" data-execution_count="2">
<div class="cell-output cell-output-stderr">
<pre><code>findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.
findfont: Font family 'Inter' not found.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-xeno-survival" class="quarto-float quarto-figure quarto-figure-center anchored" height="402" data-fig-align="center" alt="Bar chart of days survived with a gene-edited pig organ. Bennett 2022 about 60 days; Faucette 2023 about 42; Slayman 2024 about 60; Looney 2024-25 130 days; Andrews 2025-26 271 days." width="912">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-xeno-survival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="12b-industrial-xeno_files/figure-html/fig-xeno-survival-output-2.png" id="fig-xeno-survival" class="quarto-figure quarto-figure-center anchored figure-img" alt="Bar chart of days survived with a gene-edited pig organ. Bennett 2022 about 60 days; Faucette 2023 about 42; Slayman 2024 about 60; Looney 2024-25 130 days; Andrews 2025-26 271 days." width="912" height="402">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-xeno-survival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each patient was out of options. Each result taught the field something — and each death raised the question of whether the attempt was justified.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Patient</th>
<th>Year</th>
<th>Organ</th>
<th>Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>David Bennett</strong></td>
<td>2022</td>
<td>pig heart</td>
<td>lived ~2 months; first in a living human <span class="citation" data-cites="griffith2022_xeno">(<a href="#ref-griffith2022_xeno" role="doc-biblioref"><span class="nocase">Griffith et al.</span> 2022</a>)</span></td>
</tr>
<tr class="even">
<td><strong>Lawrence Faucette</strong></td>
<td>2023</td>
<td>pig heart</td>
<td>lived ~6 weeks</td>
</tr>
<tr class="odd">
<td><strong>Rick Slayman</strong></td>
<td>2024</td>
<td>pig kidney</td>
<td>first in a living patient; lived ~2 months</td>
</tr>
<tr class="even">
<td><strong>Towana Looney</strong></td>
<td>2024–25</td>
<td>pig kidney</td>
<td>organ removed after <strong>130 days</strong></td>
</tr>
<tr class="odd">
<td><strong>Tim Andrews</strong></td>
<td>2025–26</td>
<td>pig kidney</td>
<td><strong>271 days</strong> — longest to date; then received a <em>human</em> kidney</td>
</tr>
</tbody>
</table>
<div class="context-box">
<p><strong>Two things changed the question in 2025–26.</strong></p>
<p><strong>1. It stopped being a series of one-offs and became a clinical trial.</strong> In 2025 the FDA cleared the first true xenotransplant trials. Two companies, two strategies: <strong>United Therapeutics</strong> (the EXPAND study, using a <strong>10</strong>-gene-edited pig kidney; first patient transplanted at NYU Langone in November 2025) and <strong>eGenesis</strong> (a <strong>69</strong>-gene-edited pig kidney). Until now, every patient was an individual rescue attempt under compassionate-use rules. A trial means enrollment criteria, controls, and — crucially — patients who are <em>not</em> out of options in quite the same way. Recall the Chapter 3 vocabulary: this is the moment xenotransplantation acquires a <strong>clinical equipoise</strong> problem it did not previously have.</p>
<p><strong>2. Tim Andrews crossed a bridge.</strong> Andrews, a 67-year-old retired engineer from New Hampshire, received a 69-gene-edited pig kidney in January 2025. He lived with it <strong>271 days</strong> — surpassing Looney’s 130 — before declining function forced its removal in October 2025 and he returned to dialysis <span class="citation" data-cites="cnn2025_andrews_271days">(<a href="#ref-cnn2025_andrews_271days" role="doc-biblioref">CNN 2025</a>)</span>. Then, in <strong>January 2026</strong>, he received a <strong>human</strong> kidney <span class="citation" data-cites="cnn2026_xeno_bridge">(<a href="#ref-cnn2026_xeno_bridge" role="doc-biblioref">CNN 2026</a>)</span>.</p>
<p>That last step reframes the entire enterprise. If a pig organ can keep someone alive and off dialysis long enough to reach a human transplant, then xenotransplantation may not need to be a <em>permanent replacement</em> to be worth doing. It could be a <strong>bridge</strong> — the way a ventricular assist device bridges a patient to a heart. A bridge is a far easier ethical case to make than a cure: it needs to work for months, not decades.</p>
<p><strong>Write or discuss:</strong> Does reframing xeno organs as a <em>bridge</em> rather than a <em>destination</em> change whether Bennett’s 2022 surgery was justified? Does it change what you must tell the next patient in the consent conversation?</p>
</div>
</section>
<section id="what-makes-xeno-ethically-distinct" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="what-makes-xeno-ethically-distinct"><span class="header-section-number">4.4</span> What Makes Xeno Ethically Distinct</h2>
<p>Three problems set xenotransplantation apart from an ordinary transplant.</p>
<ul>
<li><strong>Animal welfare:</strong> the source pigs live their whole lives in sterile isolation, engineered and monitored as living organ factories.</li>
<li><strong>Risk to the public:</strong> a pig virus could cross into the patient and then <strong>spread to others</strong> — a <span class="key-term">xenozoonosis</span>. The patient consents; the <strong>public can’t</strong>, yet shares the risk.</li>
<li><strong>Consent under desperation:</strong> a dying patient offered a first-of-its-kind organ is not a free chooser in the ordinary sense. Is that consent, or a cornered hope?</li>
</ul>
</section>
<section id="make-it-contemporary" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="make-it-contemporary"><span class="header-section-number">4.5</span> Make It Contemporary</h2>
<div class="thought-question">
<p>David Bennett received his pig heart under an FDA “compassionate use” exception — he was too sick for the transplant waitlist. He lived two months. His son said the family hoped the attempt would “help future patients.”</p>
<ol type="1">
<li>Was it ethical to offer a brand-new, likely-fatal procedure to a man with no other options — or did desperation make real consent impossible?</li>
<li>Xenozoonosis risk falls on the whole community. Who should get a say in approving these surgeries — only patient and doctor, or the public too?</li>
<li>If the first heart transplant patients (1967) also died within weeks, does that make these attempts pioneering, or reckless?</li>
</ol>
</div>
</section>
</section>
<section id="the-ranking-that-surprises-people" class="level1 section-divider" data-number="5">
<h1 class="section-divider" data-number="5"><span class="header-section-number">5</span> The Ranking That Surprises People</h1>
<section id="the-ledger" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-ledger"><span class="header-section-number">5.1</span> The Ledger</h2>
<p>Here is the tool promised at the start. Rank an animal use by three questions.</p>
<ul>
<li><strong>Scale</strong> — how many animals? (one pig, or tens of billions?)</li>
<li><strong>Necessity</strong> — is there an easy alternative? (a salad, or nothing?)</li>
<li><strong>Benefit</strong> — how large is the human good? (a flavor, or a life?)</li>
</ul>
<p>A use scores <strong>badly</strong> when it is high-scale, unnecessary, and low-benefit — and <strong>well</strong> when it is low-scale, necessary, and high-benefit.</p>
</section>
<section id="filling-it-in" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="filling-it-in"><span class="header-section-number">5.2</span> Filling It In</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Use</th>
<th>Scale</th>
<th>Necessity</th>
<th>Benefit</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Factory-farmed bacon</strong></td>
<td>tens of billions</td>
<td>easily avoided</td>
<td>taste / cost</td>
<td><strong>worst</strong></td>
</tr>
<tr class="even">
<td><strong>Cosmetic rabbit test</strong></td>
<td>millions</td>
<td>avoidable (alternatives exist)</td>
<td>vanity product</td>
<td>bad</td>
</tr>
<tr class="odd">
<td><strong>Pig-heart transplant</strong></td>
<td>one pig</td>
<td>no alternative</td>
<td>a human life</td>
<td><strong>best</strong></td>
</tr>
<tr class="even">
<td><strong>Smarter lab mouse</strong></td>
<td>few</td>
<td>—</td>
<td>research gain, <em>but…</em></td>
<td>(see frontier)</td>
</tr>
</tbody>
</table>
<p>Read the top and bottom rows together: the <strong>everyday cheeseburger</strong> scores worse than the <strong>headline-grabbing transplant.</strong></p>
</section>
<section id="why-singer-accepts-the-pig-heart" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="why-singer-accepts-the-pig-heart"><span class="header-section-number">5.3</span> Why Singer Accepts the Pig Heart</h2>
<p>This is the result that unsettles people — and it is perfectly consistent.</p>
<ul>
<li>Singer opposes factory farming <em>because</em> it is vast suffering for a trivial, replaceable interest. The same logic, applied to xenotransplantation, points the other way.</li>
<li><strong>One</strong> pig, humanely raised, to save a human life with no alternative, is exactly the trade a utilitarian can endorse.</li>
<li>So an arch-critic of how we treat animals can <strong>support</strong> pig-heart transplants. The thing that feels “worse” because it is high-tech is, by the numbers, far better.</li>
</ul>
<p>The lesson: <strong>“creepy” and “wrong” are different properties.</strong> Novelty triggers disgust; ethics tracks suffering, necessity, and benefit.</p>
</section>
<section id="why-regan-wont-rank-them" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="why-regan-wont-rank-them"><span class="header-section-number">5.4</span> Why Regan Won’t Rank Them</h2>
<p>The rights view from Part A refuses the whole exercise — and that refusal is the strongest objection to the ledger.</p>
<div class="argument">
<div class="arg-name">
<p>The Rights Objection to the Ledger</p>
</div>
<div class="arg-source">
<p>After Tom Regan, <em>The Case for Animal Rights</em></p>
</div>
<ol type="1">
<li>A subject-of-a-life has a right not to be used merely as a means to others’ ends.</li>
<li>The transplant pig is killed precisely <em>as a means</em> — to harvest its heart.</li>
<li>Rights are not outweighed by good consequences, however large, or by small numbers.</li>
<li>So the pig-heart transplant violates the pig’s rights — and “only one pig” is no defense.</li>
</ol>
</div>
<p>For Regan, the ledger commits the original sin of utilitarianism: it prices a life that should be <strong>off the market.</strong> Where you land depends on the theory you brought from Part A.</p>
</section>
</section>
<section id="the-frontier-smarter-animals" class="level1 section-divider" data-number="6">
<h1 class="section-divider" data-number="6"><span class="header-section-number">6</span> The Frontier: Smarter Animals</h1>
<section id="uplifting" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="uplifting"><span class="header-section-number">6.1</span> Uplifting</h2>
<p>The fourth row of the ledger needs its own treatment, because it changes the rules.</p>
<ul>
<li><span class="key-term">Uplifting</span> means deliberately raising an animal’s cognitive capacities — by gene editing, drugs, or adding human cells — for example, to build a more capable research subject or a better working animal.</li>
<li>Recall the enhancement debate from genomics: we asked whether to enhance <em>humans</em>. Here the target is the animal.</li>
<li>It sounds like science fiction, but its first pieces already exist in the lab.</li>
</ul>
</section>
<section id="the-paradox" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-paradox"><span class="header-section-number">6.2</span> The Paradox</h2>
<p>Uplifting turns the moral-status question back on us.</p>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>In Part A, <strong>capacities earned moral status</strong> — sentience, being a subject-of-a-life, having a good of one’s own.</li>
<li>So if we <em>raise</em> an animal’s capacities, we <strong>raise its moral status</strong> — and our duties to it grow.</li>
<li>The better we make a research animal, the <strong>less</strong> we may be permitted to use it. Success defeats its own purpose.</li>
</ul>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:44%;">
<p>We would be <strong>manufacturing the very thing that obligates us</strong> — creating a creature, then owing it more <em>because</em> of what we made it.</p>
<p>Korsgaard’s “fellow creatures” compounds the worry: uplifting could create fellows we never intended to have.</p>
</div>
</div>
</section>
<section id="its-already-real" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="its-already-real"><span class="header-section-number">6.3</span> It’s Already Real</h2>
<p>The pieces are not hypothetical.</p>
<ul>
<li>In 2022 Stanford researchers transplanted <strong>human brain organoids</strong> — clusters of human neurons — into rat brains, where they grew, wired in, and influenced the rats’ behavior <span class="citation" data-cites="revah2022_chimera">(<a href="#ref-revah2022_chimera" role="doc-biblioref"><span class="nocase">Revah et al.</span> 2022</a>)</span>.</li>
<li>Such <span class="key-term">chimeras</span> (animals carrying human cells) are made to study human disease — but they create beings of <strong>ambiguous status:</strong> how much human neural tissue is too much?</li>
<li>Regulators now draw uneasy lines around how far this may go, especially for human cells in animal <strong>brains</strong> and reproductive systems.</li>
</ul>
</section>
<section id="thought-question-1" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="thought-question-1"><span class="header-section-number">6.4</span> Thought Question</h2>
<div class="thought-question">
<p>A lab proposes engineering mice with substantially <strong>human-like memory and problem-solving</strong>, to make Alzheimer’s research more accurate. The mice would be smarter — and, by Part A’s own criteria, would have <strong>higher moral status.</strong></p>
<ol type="1">
<li>Does making the mouse smarter make it <em>more</em> wrong to experiment on — even though the point was better research?</li>
<li>Is there a level of enhancement past which the “animal” should get human-like protections? Where, and decided by whom?</li>
<li>Could it ever be <strong>kinder</strong> to refuse to uplift — to not create a being whose new capacities only deepen its suffering in a cage?</li>
</ol>
</div>
</section>
<section id="after-youve-discussed-2" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="after-youve-discussed-2"><span class="header-section-number">6.5</span> After You’ve Discussed</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A new distinction the frontier forces: <strong>moral status as discovered vs.&nbsp;created.</strong></p>
<p>All of Part A treated status as something we <em>discover</em> — we investigate an animal and find out how much it matters. Uplifting and chimeras make status something we can <strong>create</strong>: we decide, in the lab, how much a being will matter, and thereby how much we’ll owe it.</p>
<p>That is genuinely new in ethics. We are used to asking “what do we owe this creature?” We are not used to choosing, in advance, <strong>how much we’ll be obligated</strong> — and then building the creature to match.</p>
</div>
</div>
</section>
</section>
<section id="connecting-threads" class="level1 section-divider" data-number="7">
<h1 class="section-divider" data-number="7"><span class="header-section-number">7</span> Connecting Threads</h1>
<section id="the-course-applied-to-animals" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-course-applied-to-animals"><span class="header-section-number">7.1</span> The Course, Applied to Animals</h2>
<p>The moral-status question runs under half this course. Each chapter offered a criterion — and each one can be aimed at animals.</p>
<div class="cell" data-fig-width="9.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<svg width="912" height="480" viewbox="0.00 0.00 256.04 258.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 254)">
<title>threads</title>
<!-- center -->
<g id="node1" class="node">
<title>center</title>
<ellipse fill="#0e7c86" stroke="#095058" stroke-width="1.4" cx="191.95" cy="-122" rx="56.18" ry="28.07"></ellipse>
<text text-anchor="middle" x="191.95" y="-125" font-family="Inter" font-size="10.00" fill="#ffffff">Does it apply</text>
<text text-anchor="middle" x="191.95" y="-113" font-family="Inter" font-size="10.00" fill="#ffffff">to animals?</text>
</g>
<!-- a -->
<g id="node2" class="node">
<title>a</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M83.13,-250C83.13,-250 16.73,-250 16.73,-250 10.73,-250 4.73,-244 4.73,-238 4.73,-238 4.73,-210 4.73,-210 4.73,-204 10.73,-198 16.73,-198 16.73,-198 83.13,-198 83.13,-198 89.13,-198 95.13,-204 95.13,-210 95.13,-210 95.13,-238 95.13,-238 95.13,-244 89.13,-250 83.13,-250"></path>
<text text-anchor="middle" x="49.93" y="-233" font-family="Inter" font-size="10.00" fill="#0f172a">Abortion:</text>
<text text-anchor="middle" x="49.93" y="-221" font-family="Inter" font-size="10.00" fill="#0f172a">'future like ours'</text>
<text text-anchor="middle" x="49.93" y="-209" font-family="Inter" font-size="10.00" fill="#0f172a">(Marquis)</text>
</g>
<!-- a&#45;&gt;center -->
<g id="edge1" class="edge">
<title>a-&gt;center</title>
<path fill="none" stroke="#94a3b8" stroke-width="1.2" d="M87.57,-197.87C91.72,-194.89 95.88,-191.88 99.86,-189 116.77,-176.73 135.37,-163.08 151.33,-151.32"></path>
<polygon fill="#94a3b8" stroke="#94a3b8" stroke-width="1.2" points="159.41,-145.36 154.03,-154.92 155.44,-148.41 151.42,-151.38 151.36,-151.29 151.3,-151.21 155.32,-148.25 148.69,-147.67 159.41,-145.36 159.41,-145.36"></polygon>
</g>
<!-- g -->
<g id="node3" class="node">
<title>g</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M81.58,-180C81.58,-180 18.28,-180 18.28,-180 12.28,-180 6.28,-174 6.28,-168 6.28,-168 6.28,-140 6.28,-140 6.28,-134 12.28,-128 18.28,-128 18.28,-128 81.58,-128 81.58,-128 87.58,-128 93.58,-134 93.58,-140 93.58,-140 93.58,-168 93.58,-168 93.58,-174 87.58,-180 81.58,-180"></path>
<text text-anchor="middle" x="49.93" y="-163" font-family="Inter" font-size="10.00" fill="#0f172a">Genetics:</text>
<text text-anchor="middle" x="49.93" y="-151" font-family="Inter" font-size="10.00" fill="#0f172a">making a being</text>
<text text-anchor="middle" x="49.93" y="-139" font-family="Inter" font-size="10.00" fill="#0f172a">to be used</text>
</g>
<!-- g&#45;&gt;center -->
<g id="edge2" class="edge">
<title>g-&gt;center</title>
<path fill="none" stroke="#94a3b8" stroke-width="1.2" d="M93.7,-144.23C105.38,-141.56 118.25,-138.61 130.7,-135.77"></path>
<polygon fill="#94a3b8" stroke="#94a3b8" stroke-width="1.2" points="140.57,-133.51 131.83,-140.13 135.72,-134.72 130.85,-135.84 130.82,-135.74 130.8,-135.64 135.67,-134.53 129.82,-131.35 140.57,-133.51 140.57,-133.51"></polygon>
</g>
<!-- e -->
<g id="node4" class="node">
<title>e</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M85.97,-110C85.97,-110 13.89,-110 13.89,-110 7.89,-110 1.89,-104 1.89,-98 1.89,-98 1.89,-82 1.89,-82 1.89,-76 7.89,-70 13.89,-70 13.89,-70 85.97,-70 85.97,-70 91.97,-70 97.97,-76 97.97,-82 97.97,-82 97.97,-98 97.97,-98 97.97,-104 91.97,-110 85.97,-110"></path>
<text text-anchor="middle" x="49.93" y="-93" font-family="Inter" font-size="10.00" fill="#0f172a">End of life:</text>
<text text-anchor="middle" x="49.93" y="-81" font-family="Inter" font-size="10.00" fill="#0f172a">killing for benefit</text>
</g>
<!-- e&#45;&gt;center -->
<g id="edge3" class="edge">
<title>e-&gt;center</title>
<path fill="none" stroke="#94a3b8" stroke-width="1.2" d="M98.33,-100.83C108.66,-103.19 119.72,-105.72 130.48,-108.18"></path>
<polygon fill="#94a3b8" stroke="#94a3b8" stroke-width="1.2" points="140.24,-110.41 129.49,-112.57 135.34,-109.39 130.47,-108.28 130.49,-108.18 130.51,-108.08 135.39,-109.2 131.49,-103.8 140.24,-110.41 140.24,-110.41"></polygon>
</g>
<!-- s -->
<g id="node5" class="node">
<title>s</title>
<path fill="#e6f1f2" stroke="#0e7c86" stroke-width="1.4" d="M87.79,-52C87.79,-52 12.07,-52 12.07,-52 6.07,-52 0.07,-46 0.07,-40 0.07,-40 0.07,-12 0.07,-12 0.07,-6 6.07,0 12.07,0 12.07,0 87.79,0 87.79,0 93.79,0 99.79,-6 99.79,-12 99.79,-12 99.79,-40 99.79,-40 99.79,-46 93.79,-52 87.79,-52"></path>
<text text-anchor="middle" x="49.93" y="-35" font-family="Inter" font-size="10.00" fill="#0f172a">Status:</text>
<text text-anchor="middle" x="49.93" y="-23" font-family="Inter" font-size="10.00" fill="#0f172a">sentience, subject-</text>
<text text-anchor="middle" x="49.93" y="-11" font-family="Inter" font-size="10.00" fill="#0f172a">of-a-life</text>
</g>
<!-- s&#45;&gt;center -->
<g id="edge4" class="edge">
<title>s-&gt;center</title>
<path fill="none" stroke="#94a3b8" stroke-width="1.2" d="M89.19,-52.23C107.87,-65.04 130.37,-80.47 149.46,-93.55"></path>
<polygon fill="#94a3b8" stroke="#94a3b8" stroke-width="1.2" points="157.97,-99.39 147.17,-97.44 153.79,-96.64 149.66,-93.81 149.72,-93.73 149.77,-93.65 153.9,-96.48 152.26,-90.02 157.97,-99.39 157.97,-99.39"></polygon>
</g>
</g>
</svg>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>We’ll walk three of these, because each <em>changes its verdict</em> when the patient is a pig.</p>
</section>
<section id="thread-1-the-argument-from-abortion" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="thread-1-the-argument-from-abortion"><span class="header-section-number">7.2</span> Thread 1 — The Argument from Abortion</h2>
<div class="thought-question">
<p>Don Marquis argued abortion is wrong because it deprives the fetus of a <span class="key-term">future like ours</span> — a future of valuable experiences <span class="citation" data-cites="marquis1989">(<a href="#ref-marquis1989" role="doc-biblioref">Marquis 1989</a>)</span>. The fetus isn’t conscious yet, but it has that future to lose.</p>
<p>Now apply it. A healthy pig also has a future of experiences it values — and the transplant ends it.</p>
<ol type="1">
<li>If a valuable future makes killing a fetus wrong, why doesn’t a pig’s future make killing the pig wrong?</li>
<li>Can you keep Marquis’s argument against abortion <strong>and</strong> eat bacon — without special pleading?</li>
<li>Does the pig’s future differ from a human’s in a way that <em>matters</em>, or only in a way that’s <em>convenient</em>?</li>
</ol>
</div>
</section>
<section id="threads-2-and-3-genetics-and-end-of-life" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="threads-2-and-3-genetics-and-end-of-life"><span class="header-section-number">7.3</span> Threads 2 and 3 — Genetics and End of Life</h2>
<p>Two more callbacks, stated briefly so you can carry them into discussion.</p>
<div class="columns">
<div class="column" style="width:48%;">
<p><strong>From genetics.</strong> We worried about creating a <strong>savior sibling</strong> — a child conceived to donate to another. A transplant pig is engineered, born, and killed to be used. Is “made to be used” worse for a person than for a pig — and is <em>creating</em> a life for parts different from <em>taking</em> one?</p>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<p><strong>From end of life.</strong> We let humans accept risk or death for others (research subjects, living donors). The pig’s death is <strong>killing for benefit</strong>, without consent. Is that worse than the risks we let humans choose — or does the pig’s inability to consent change the kind of act it is?</p>
</div>
</div>
</section>
</section>
<section id="where-this-leaves-us" class="level1 section-divider" data-number="8">
<h1 class="section-divider" data-number="8"><span class="header-section-number">8</span> Where This Leaves Us</h1>
<section id="wrap-up" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="wrap-up"><span class="header-section-number">8.1</span> Wrap-Up</h2>
<div class="recap">
<p>We ranked four uses of animals and built a tool — <strong>scale, necessity, benefit</strong> — that reorders our intuitions: the industrial cheeseburger comes out worse than the gene-edited pig heart, and a critic of factory farming like Singer can consistently accept xenotransplantation. Regan’s rights view refuses the ranking entirely, which is why the verdict still depends on the theory you hold. Along the way the food system showed how animal harm and <strong>human</strong> harm converge — antibiotic resistance, pandemics — and the frontier of <strong>uplifting</strong> showed we can now <em>create</em> the moral status we then must honor. The threads from abortion, genetics, and end-of-life all reach the same pig, and none of them lets us off easily.</p>
</div>
</section>
<section id="paired-case" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="paired-case"><span class="header-section-number">8.2</span> Paired Case</h2>
<p>The whole lecture comes down to one operating room and one desperate patient.</p>
<blockquote class="blockquote">
<p><strong>Paired case:</strong> <a href="../cases/12-bennett-xenotransplant.html">David Bennett and the First Pig-Heart Transplant</a></p>
</blockquote>
</section>
<section id="review-questions" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="review-questions"><span class="header-section-number">8.3</span> Review Questions</h2>
<div class="review-questions">
<div class="review-item review-recall">
<p><span class="review-label">Recall</span></p>
<p>Name the three factors in the scale–necessity–benefit ledger, and use them to explain why factory-farmed bacon ranks worse than a pig-heart transplant.</p>
</div>
<div class="review-item review-apply">
<p><span class="review-label">Apply</span></p>
<p>A company wants to gene-edit chickens to grow faster and resist a barn virus, cutting both cost and antibiotic use. Run it through the ledger and through the direct/indirect-harm distinction. Where does it help, and whom?</p>
</div>
<div class="review-item review-debate">
<p><span class="review-label">Debate</span></p>
<p>If we could uplift research animals to get better data, should we — knowing that doing so raises their moral status and our duties to them? Defend a yes or a no.</p>
</div>
</div>
</section>
<section id="key-terms" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">8.4</span> Key Terms</h2>
<ul>
<li><strong>CAFO</strong> — concentrated animal feeding operation; the high-density industrial farm model.</li>
<li><strong>Antibiotic resistance</strong> — bacteria evolving to survive drugs; driven partly by routine livestock use.</li>
<li><strong>Translation gap</strong> — the frequent failure of animal results to predict human outcomes.</li>
<li><strong>Xenotransplantation</strong> — transplanting organs or tissue from another species into humans.</li>
<li><strong>Xenozoonosis</strong> — an infection crossing from the source animal to the human recipient and potentially the public.</li>
<li><strong>Uplifting</strong> — deliberately enhancing an animal’s cognitive capacities.</li>
<li><strong>Chimera</strong> — an organism containing cells from another species, e.g., human neurons in an animal brain.</li>
<li><strong>Future like ours (Marquis)</strong> — the view that killing is wrong because it deprives a being of a valuable future.</li>
<li><strong>Scale–necessity–benefit ledger</strong> — the framework for ranking animal uses by number harmed, availability of alternatives, and size of the good.</li>
</ul>
</section>
<section id="further-reading" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">8.5</span> Further Reading</h2>
<ul>
<li>Singer, Peter. <em>Animal Liberation Now</em>. Harper Perennial, 2023 — the updated case against industrial farming.</li>
<li>Griffith, Bartley P., et al.&nbsp;“Genetically Modified Porcine-to-Human Cardiac Xenotransplantation.” <em>New England Journal of Medicine</em>, 2022 — the Bennett case, by the surgical team.</li>
<li>Korsgaard, Christine. <em>Fellow Creatures</em>. Oxford University Press, 2018 — duties to animals, including the created ones.</li>
</ul>
</section>
<section id="references" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="references"><span class="header-section-number">8.6</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-cnn2025_andrews_271days" class="csl-entry" role="listitem">
CNN. 2025. <em>Pig Kidney Removed from New Hampshire Man Tim Andrews 271 Days After Transplant</em>. CNN Health, October 27, 2025. <a href="https://www.cnn.com/2025/10/27/health/pig-kidney-transplant-tim-andrews">https://www.cnn.com/2025/10/27/health/pig-kidney-transplant-tim-andrews</a>.
</div>
<div id="ref-cnn2026_xeno_bridge" class="csl-entry" role="listitem">
CNN. 2026. <em>Man Who Received Experimental Pig Kidney Transplant Now Has a Human Organ</em>. CNN Health, January 16, 2026. <a href="https://edition.cnn.com/2026/01/16/health/pig-kidney-human-organ-transplant">https://edition.cnn.com/2026/01/16/health/pig-kidney-human-organ-transplant</a>.
</div>
<div id="ref-ec2025_roadmap" class="csl-entry" role="listitem">
European Commission. 2025. <em>Roadmap Towards Phasing Out Animal Testing for Chemical Safety Assessments</em>. European Commission, Directorate-General for Environment. <a href="https://environment.ec.europa.eu/">https://environment.ec.europa.eu/</a>.
</div>
<div id="ref-griffith2022_xeno" class="csl-entry" role="listitem">
<span class="nocase">Griffith, Bartley P., Corbin E. Goerlich, Avneesh K. Singh, et al.</span> 2022. <span>“Genetically Modified Porcine-to-Human Cardiac Xenotransplantation.”</span> <em>New England Journal of Medicine</em> 387 (1): 35–44. <a href="https://doi.org/10.1056/NEJMoa2201422">https://doi.org/10.1056/NEJMoa2201422</a>.
</div>
<div id="ref-marquis1989" class="csl-entry" role="listitem">
Marquis, Don. 1989. <span>“Why Abortion Is Immoral.”</span> <em>The Journal of Philosophy</em> 86 (4): 183–202. <a href="https://doi.org/10.2307/2026961">https://doi.org/10.2307/2026961</a>.
</div>
<div id="ref-oneill2016_amr" class="csl-entry" role="listitem">
O’Neill, Jim. 2016. <em>Tackling Drug-Resistant Infections Globally: Final Report and Recommendations</em>. Review on Antimicrobial Resistance, Wellcome Trust and HM Government. <a href="https://amr-review.org/">https://amr-review.org/</a>.
</div>
<div id="ref-revah2022_chimera" class="csl-entry" role="listitem">
<span class="nocase">Revah, Omer, Felicity Gore, Kevin W. Kelley, et al.</span> 2022. <span>“Maturation and Circuit Integration of Transplanted Human Cortical Organoids.”</span> <em>Nature</em> 610: 319–26. <a href="https://doi.org/10.1038/s41586-022-05277-w">https://doi.org/10.1038/s41586-022-05277-w</a>.
</div>
<div id="ref-fda_modernization2022" class="csl-entry" role="listitem">
United States Congress. 2022. <em>FDA Modernization Act 2.0</em>. 117th Congress.
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="https://creativecommons.org/licenses/by-nc/4.0/"><img src="https://licensebuttons.net/l/by-nc/4.0/88x31.png" class="img-fluid" alt="CC BY-NC 4.0"></a> Licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Brendan Shea</p>
</div>
  </div>
</footer>




</body></html>